echo WEBFLOW_API_TOKEN=$WEBFLOW_API_TOKEN
echo WEBFLOW_SITE_ID=$WEBFLOW_SITE_ID

echo ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
echo OPENAI_API_KEY=$OPENAI_API_KEY
echo YOUTUBE_API_KEY=$YOUTUBE_API_KEY
echo GEMINI_API_KEY=$GEMINI_API_KEY
echo GOOGLE_API_KEY=$GOOGLE_API_KEY
